package naogateway.value;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAWCamserver_messages.proto

public final class HAWCamserverMessages {
  private HAWCamserverMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CamRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 resolution = 1;
    boolean hasResolution();
    int getResolution();
    
    // optional uint32 colorSpace = 2;
    boolean hasColorSpace();
    int getColorSpace();
    
    // optional uint32 fps = 3;
    boolean hasFps();
    int getFps();
  }
  public static final class CamRequest extends
      com.google.protobuf.GeneratedMessage
      implements CamRequestOrBuilder {
    // Use CamRequest.newBuilder() to construct.
    private CamRequest(Builder builder) {
      super(builder);
    }
    private CamRequest(boolean noInit) {}
    
    private static final CamRequest defaultInstance;
    public static CamRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CamRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HAWCamserverMessages.internal_static_CamRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HAWCamserverMessages.internal_static_CamRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 resolution = 1;
    public static final int RESOLUTION_FIELD_NUMBER = 1;
    private int resolution_;
    public boolean hasResolution() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResolution() {
      return resolution_;
    }
    
    // optional uint32 colorSpace = 2;
    public static final int COLORSPACE_FIELD_NUMBER = 2;
    private int colorSpace_;
    public boolean hasColorSpace() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getColorSpace() {
      return colorSpace_;
    }
    
    // optional uint32 fps = 3;
    public static final int FPS_FIELD_NUMBER = 3;
    private int fps_;
    public boolean hasFps() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getFps() {
      return fps_;
    }
    
    private void initFields() {
      resolution_ = 0;
      colorSpace_ = 0;
      fps_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, resolution_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, colorSpace_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, fps_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, resolution_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, colorSpace_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, fps_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HAWCamserverMessages.CamRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HAWCamserverMessages.CamRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HAWCamserverMessages.CamRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HAWCamserverMessages.CamRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HAWCamserverMessages.CamRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HAWCamserverMessages.CamRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HAWCamserverMessages.internal_static_CamRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HAWCamserverMessages.internal_static_CamRequest_fieldAccessorTable;
      }
      
      // Construct using HAWCamserverMessages.CamRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resolution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        colorSpace_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fps_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HAWCamserverMessages.CamRequest.getDescriptor();
      }
      
      public HAWCamserverMessages.CamRequest getDefaultInstanceForType() {
        return HAWCamserverMessages.CamRequest.getDefaultInstance();
      }
      
      public HAWCamserverMessages.CamRequest build() {
        HAWCamserverMessages.CamRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HAWCamserverMessages.CamRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        HAWCamserverMessages.CamRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HAWCamserverMessages.CamRequest buildPartial() {
        HAWCamserverMessages.CamRequest result = new HAWCamserverMessages.CamRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resolution_ = resolution_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.colorSpace_ = colorSpace_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fps_ = fps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HAWCamserverMessages.CamRequest) {
          return mergeFrom((HAWCamserverMessages.CamRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HAWCamserverMessages.CamRequest other) {
        if (other == HAWCamserverMessages.CamRequest.getDefaultInstance()) return this;
        if (other.hasResolution()) {
          setResolution(other.getResolution());
        }
        if (other.hasColorSpace()) {
          setColorSpace(other.getColorSpace());
        }
        if (other.hasFps()) {
          setFps(other.getFps());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resolution_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              colorSpace_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fps_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 resolution = 1;
      private int resolution_ ;
      public boolean hasResolution() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResolution() {
        return resolution_;
      }
      public Builder setResolution(int value) {
        bitField0_ |= 0x00000001;
        resolution_ = value;
        onChanged();
        return this;
      }
      public Builder clearResolution() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resolution_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 colorSpace = 2;
      private int colorSpace_ ;
      public boolean hasColorSpace() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getColorSpace() {
        return colorSpace_;
      }
      public Builder setColorSpace(int value) {
        bitField0_ |= 0x00000002;
        colorSpace_ = value;
        onChanged();
        return this;
      }
      public Builder clearColorSpace() {
        bitField0_ = (bitField0_ & ~0x00000002);
        colorSpace_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 fps = 3;
      private int fps_ ;
      public boolean hasFps() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getFps() {
        return fps_;
      }
      public Builder setFps(int value) {
        bitField0_ |= 0x00000004;
        fps_ = value;
        onChanged();
        return this;
      }
      public Builder clearFps() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fps_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CamRequest)
    }
    
    static {
      defaultInstance = new CamRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CamRequest)
  }
  
  public interface CamResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes imageData = 1;
    boolean hasImageData();
    com.google.protobuf.ByteString getImageData();
    
    // optional string error = 2;
    boolean hasError();
    String getError();
  }
  public static final class CamResponse extends
      com.google.protobuf.GeneratedMessage
      implements CamResponseOrBuilder {
    // Use CamResponse.newBuilder() to construct.
    private CamResponse(Builder builder) {
      super(builder);
    }
    private CamResponse(boolean noInit) {}
    
    private static final CamResponse defaultInstance;
    public static CamResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CamResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HAWCamserverMessages.internal_static_CamResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HAWCamserverMessages.internal_static_CamResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes imageData = 1;
    public static final int IMAGEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString imageData_;
    public boolean hasImageData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    
    // optional string error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private java.lang.Object error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          error_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, imageData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, imageData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HAWCamserverMessages.CamResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HAWCamserverMessages.CamResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HAWCamserverMessages.CamResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HAWCamserverMessages.CamResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HAWCamserverMessages.CamResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HAWCamserverMessages.CamResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HAWCamserverMessages.internal_static_CamResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HAWCamserverMessages.internal_static_CamResponse_fieldAccessorTable;
      }
      
      // Construct using HAWCamserverMessages.CamResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        imageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HAWCamserverMessages.CamResponse.getDescriptor();
      }
      
      public HAWCamserverMessages.CamResponse getDefaultInstanceForType() {
        return HAWCamserverMessages.CamResponse.getDefaultInstance();
      }
      
      public HAWCamserverMessages.CamResponse build() {
        HAWCamserverMessages.CamResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HAWCamserverMessages.CamResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        HAWCamserverMessages.CamResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HAWCamserverMessages.CamResponse buildPartial() {
        HAWCamserverMessages.CamResponse result = new HAWCamserverMessages.CamResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imageData_ = imageData_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HAWCamserverMessages.CamResponse) {
          return mergeFrom((HAWCamserverMessages.CamResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HAWCamserverMessages.CamResponse other) {
        if (other == HAWCamserverMessages.CamResponse.getDefaultInstance()) return this;
        if (other.hasImageData()) {
          setImageData(other.getImageData());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              imageData_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              error_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes imageData = 1;
      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImageData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        imageData_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }
      
      // optional string error = 2;
      private java.lang.Object error_ = "";
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setError(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      void setError(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:CamResponse)
    }
    
    static {
      defaultInstance = new CamResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CamResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CamRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CamRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CamResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CamResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033HAWCamserver_messages.proto\"A\n\nCamRequ" +
      "est\022\022\n\nresolution\030\001 \001(\r\022\022\n\ncolorSpace\030\002 " +
      "\001(\r\022\013\n\003fps\030\003 \001(\r\"/\n\013CamResponse\022\021\n\timage" +
      "Data\030\001 \001(\014\022\r\n\005error\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CamRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CamRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CamRequest_descriptor,
              new java.lang.String[] { "Resolution", "ColorSpace", "Fps", },
              HAWCamserverMessages.CamRequest.class,
              HAWCamserverMessages.CamRequest.Builder.class);
          internal_static_CamResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CamResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CamResponse_descriptor,
              new java.lang.String[] { "ImageData", "Error", },
              HAWCamserverMessages.CamResponse.class,
              HAWCamserverMessages.CamResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
