/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParamFrame.java
 *
 * Created on Sep 7, 2012, 6:41:04 PM
 */
package naogateway.value.simpleTestGUI;

import naogateway.value.Hawactormsg.MixedValue;

/**
 *
 * @author david
 */
public class ParamFrame extends javax.swing.JFrame {
    private ProtobufListModel params;
    
    /** Creates new form ParamFrame */
    public ParamFrame(ProtobufListModel params) {
        this.params = params;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        cbxValue = new javax.swing.JComboBox();

        jTextField2.setText("jTextField2");
        jTextField2.setName("jTextField2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parameter erstellen");

        jLabel1.setText("Typ");
        jLabel1.setName("jLabel1"); // NOI18N

        cbxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "String", "int", "float", "boolean" }));
        cbxType.setName("cbxType"); // NOI18N
        cbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeChanged(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createParameter(evt);
            }
        });

        jLabel2.setText("Wert");
        jLabel2.setName("jLabel2"); // NOI18N

        txtValue.setText("Hello");
        txtValue.setName("txtValue"); // NOI18N

        cbxValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));
        cbxValue.setEnabled(false);
        cbxValue.setName("cbxValue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxType, 0, 122, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValue, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void typeChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeChanged
    String type = (String)cbxType.getSelectedItem();
    if (type.equals("boolean")) {
        txtValue.setEnabled(false);
        cbxValue.setEnabled(true);
    } else {
        txtValue.setEnabled(true);
        cbxValue.setEnabled(false);
    }   
}//GEN-LAST:event_typeChanged

private void createParameter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createParameter
    String type = (String)cbxType.getSelectedItem();
    if (type.equals("boolean")) {
        boolean value = cbxValue.getSelectedItem().equals("true");
        params.addElement(MixedValue.newBuilder().setBool(value).build());
    } else if (type.equals("String")) {
        String value = txtValue.getText();
        params.addElement(MixedValue.newBuilder().setString(value).build());
    } else if (type.equals("int")) {
        Integer value = Integer.parseInt(txtValue.getText());
        params.addElement(MixedValue.newBuilder().setInt(value).build());
    } else if (type.equals("float")) {
        Float value = Float.parseFloat(txtValue.getText());
        params.addElement(MixedValue.newBuilder().setFloat(value).build());
    } else {
        System.out.println("Need to implment " + type);
    }
    this.dispose();
}//GEN-LAST:event_createParameter

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbxType;
    private javax.swing.JComboBox cbxValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
